### ISSUE TITLE
Idea for new module

### ISSUE THREAD

**Issue by ingbrzy** [BurgerZ/WSM-Project#5]
Is possible make a module for enable Google Now for all languages..? I saw that mod on XDA....

**Comment by BurgerZ** [comment]
I think it's possible, why not)

**Comment by ingbrzy** [comment]
also new idea.. removing special characters from the letters of some language like CZ/SK to keep 160 letters in SMS message...

**Comment by ghost** [comment]
i don't know for you, but for me most of the lockscreens and clocks from the theme market are unusable because of those chinese lunar days and chinese signs :
if someone can write a module that remove those chinese days and fix the time/date format, can be very good :) i don't even know if is that possible..

![screenshot_2013-10-15-02-08-32 1](https://f.cloud.github.com/assets/812995/1332386/ad65d83a-3579-11e3-9d66-1a130a9e5ba6.png)
![screenshot_2013-10-15-02-08-25 1](https://f.cloud.github.com/assets/812995/1332389/b86ef39c-3579-11e3-9e25-51d891d2bedd.png)
![screenshot_2013-10-15-11-05-40 1](https://f.cloud.github.com/assets/812995/1332392/c12810c2-3579-11e3-98bb-dfa6dc0f6a2f.png)

**Comment by zdunex25** [comment]
Is it possible for you to add an option (to mitools) that allows us to hide icons from desktop?

**Comment by BurgerZ** [comment]
@zdunex25 I thought about it. I could try, today I'm free enough.

**Comment by zdunex25** [comment]
It would be just great, I saw similar module, but unfortunately for google launchers.
SRC: https://github.com/depressiveRobot/HideAppsXposed

**Comment by BurgerZ** [comment]
MIUI Home application has different way to load and hanlde apps icons on the working space.

**Comment by zdunex25** [comment]
I only know how to hide icons by editing app itself, but it's not handy.

**Comment by BurgerZ** [comment]
@zdunex25 check your email.

**Comment by zdunex25** [comment]
Wrote you back :)
